.PHONY: clean All

All:
	@echo "----------Building project:[ using_data_formats_using_scanf - Debug ]----------"
	@cd "using_data_formats_using_scanf" && "$(MAKE)" -f  "using_data_formats_using_scanf.mk"
clean:
	@echo "----------Cleaning project:[ using_data_formats_using_scanf - Debug ]----------"
	@cd "using_data_formats_using_scanf" && "$(MAKE)" -f  "using_data_formats_using_scanf.mk" clean
