.PHONY: clean All

All:
	@echo "----------Building project:[ bit_operators - Debug ]----------"
	@cd "bit_operators" && "$(MAKE)" -f  "bit_operators.mk"
clean:
	@echo "----------Cleaning project:[ bit_operators - Debug ]----------"
	@cd "bit_operators" && "$(MAKE)" -f  "bit_operators.mk" clean
